# -- Soulseek --

username = YOUR_SOULSEEK_USER
password = YOUR_SOULSEEK_PASSWORD

# -- Spotify --

# Optionally provide your own Spotify app instead of the hardcoded one (make sure to add "http://127.0.0.1:48721/callback" callback)
spotify-id = YOUR_CLIENT_ID
spotify-secret = YOUR_CLIENT_SECRET

# Provide refresh token to access liked music and other private playlists (get the token from `make spotify-login` command)
spotify-refresh = YOUR_REFRESH_TOKEN

# -- Tracks config --

pref-format = flac
pref-min-bitrate = 320
min-bitrate = 256
max-bitrate = 2500
pref-max-samplerate = 48000
min-samplerate = 44100
pref-min-bitdepth = 16
fast-search = true

# DJ friendly config summary:
# - Prioritizes FLAC: over all other formats 
# - Requires minimum 256kbps: for non-FLAC files, prefers 320+kbps\
# - Enforces CD-quality minimum: (44.1kHz sample rate) 
# - Prefers standard sample rates: (≤48kHz) and 16+ bit depth 
# - Fake file protection: (max 2500kbps bitrate limit)
# - Fast search enabled to download immediately when matching FLAC found (faster, though may miss even better quality files)
